name: Linux x86_64

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_call, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job
      # can access it
      - uses: actions/checkout@v3

      - name: setup prerequisites
        run: |
          sudo apt update
          sudo apt install automake libcurl4-openssl-dev zlib1g-dev

      - name: build
        run: ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: cpuminer-linux-x86_64
          path: cpuminer
