name: MSYS2 build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_call, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job
      # can access it
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-cc mingw-w64-x86_64-autotools mingw-w64-x86_64-curl mingw-w64-x86_64-openssl mingw-w64-x86_64-zlib

      - name: build
        run: |
          ./build.sh
          mv cpuminer cpuminer-msys2

      - uses: actions/upload-artifact@v4
        with:
          name: cpuminer-msys2
          path: cpuminer-msys2
